### ISSUE TITLE
Remove .env file

### ISSUE THREAD

**Issue by mpagels** [NimaHBB/server#1]
Hey Nima,

just saw that you pushed your `.env` to Github. And your `node_modules` folders as well.

You don't have a `.gitignore` file to tell `git` which files not to version control.

I recommend fixing this asap.

I found a very good article on how to remove it:
https://daily-dev-tips.com/posts/removing-a-env-file-from-git-history/

**Comment by NimaHBB** [comment]
Hi Martin,
danke für Review und auch für das Link.
Okay ich gucke es.
diese Server Repo ist nur für Test.
Ich habe viel Probleme mit Heroku! :'(

**Comment by NimaHBB** [comment]
Ich habe sie gelöscht.

**Comment by NimaHBB** [comment]
jetzt habe ich es gemerckt dass statt .gitignore, habe ich in .gitinit geschrieben  :D
